# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run export
      - name: FTP Deployer
        # You may pin to the exact commit or the version.
        # uses: sand4rt/ftp-deployer@b4d8a88f104b46a1bcfac8f69b3413986cc0ce28
        uses: sand4rt/ftp-deployer@v1.3
        with:
          # SFTP on
          sftp: true
          # FTP host URL like: ftp.host.com or sftp.host.com
          host: ssh.thaudal.com
          # FTP port
          port: 22
          # Ftp username
          username: thaudal.com
          # Ftp password
          password: ${{ secrets.FtpPassword }}
          # The remote folder location of your FTP server
          remote_folder: /www/
          # The local folder location
          local_folder: out
          # Remove existing files insie FTP remote folder
          cleanup: true

